{% set name = "json-repair" %}
{% set version = "0.29.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json_repair-{{ version }}.tar.gz
  sha256: 2116a131ed199e51a97e21a27839a86f8ef6422aa046a078b763320a45d1850d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - json_repair
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mangiucugna/json_repair/
  summary: A package to repair broken json strings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
