{% set name = "json-repair" %}
{% set version = "0.54.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/json_repair-{{ version }}.tar.gz
  sha256: 4b6b62ce17f1a505b220fa4aadba1fc37dc9c221544f158471efe3775620bad6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - json_repair
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mangiucugna/json_repair/
  summary: A package to repair broken json strings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
