schema_version: 1

context:
  name: json-repair
  version: "0.61.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/json_repair-${{ version }}.tar.gz
  sha256: a3754543f050093efcda6c9ab00b20a236b5d082c8c622bc65b88fa74ff8d51f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - json_repair
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A package to repair broken json strings
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mangiucugna/json_repair/

extra:
  recipe-maintainers:
    - jan-janssen
