schema_version: 1

context:
  name: json-repair
  version: "0.59.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/json_repair-${{ version }}.tar.gz
  sha256: 747948f5342ff0de28a5467d25b4ed4690291362311eb936752473345f7a2f51

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - json_repair
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A package to repair broken json strings
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mangiucugna/json_repair/

extra:
  recipe-maintainers:
    - jan-janssen
