schema_version: 1

context:
  name: json-repair
  version: "0.59.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/json_repair-${{ version }}.tar.gz
  sha256: 2e4b85537c752d8a513ea28fdad891e5ede32c83de745366b97f648b8c34ede7

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - json_repair
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A package to repair broken json strings
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mangiucugna/json_repair/

extra:
  recipe-maintainers:
    - jan-janssen
